name: Joshua Fisher
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73736700-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0a08'
    - '#fdfdfd'
    - '#474e61'
    - '#99bccf'
    - '#e68036'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
