name: Joshua Fisher
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73736700-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bebebe'
    - '#242424'
    - '#505050'
    - '#919191'
  brandStrength: 0.3125
  lightness: 0.5068286908790469
  saturation: 0.30688812490552664
  rhythmicContrast: 0.25
purpose: []
