name: Joshua Fisher
favicon: null
layout_spectrum: 0.63515
typography_spectrum: 0.75075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73736700-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b2d2a'
    - '#4966c2'
    - '#2b4498'
    - '#a96757'
    - '#ceafad'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 1
purpose: []
